#pragma once

#include "Interfaces.h"
#include "VLVariable.h"

/**
 * @class Stop
 * @brief Represents a single stop in a trip, including start location, distance, and fuel usage.
 *
 * This class implements a COM-style reference-counted object used by TripPlanner.
 * Each Stop stores basic trip metrics and provides simple setters and a formatted print method.
 */
class Stop : public IUnknown
{
public:
	/**
	 * @brief Constructs a new Stop object with default values.
	 */
	Stop();

	/**
	 * @brief Destructor for Stop.
	 */
	~Stop();

	/**
	 * @brief Standard COM QueryInterface implementation.
	 * @param riid The requested interface ID.
	 * @param ppvObj Receives the interface pointer if supported.
	 * @return S_OK if the interface is supported, otherwise E_NOINTERFACE.
	 */
	HRESULT __stdcall QueryInterface(REFIID riid, LPVOID* ppvObj);

	/**
	 * @brief Increments the COM reference count.
	 * @return The new reference count.
	 */
	ULONG __stdcall AddRef();

	/**
	 * @brief Decrements the COM reference count and deletes the object when it reaches zero.
	 * @return The new reference count.
	 */
	ULONG __stdcall Release();
	HRESULT __stdcall Properties(IUnknown** iProp);

	void Print() { wprintf(L"Distance: %d\tFuel Used:\t%fTravel Time\t%dh:%dm\n", m_distance, m_fuelUsed, m_travelTime / 60, m_travelTime % 60); }
	

	inline void Distance(UINT nDistance) { m_distance = nDistance; }
	inline UINT Distance() { return m_distance; }
	inline void FuelUsed(double fFuelUsed) { m_fuelUsed = fFuelUsed; }
	inline void TravelTime(UINT nTravelTime) { m_travelTime = nTravelTime; }

private:
	int m_cRef;
	VLVariable* m_pStart;
	VariableCollection m_properties;
	
	UINT m_distance;
	double m_fuelUsed;
	int m_travelTime;
};


/**
 * @class TripPlanner
 * @brief Manages a collection of stops and exposes COM-accessible trip-planning functionality.
 *
 * TripPlanner implements the TripPlannerInf::ITRIPPLANNER interface and provides:
 * - Adding and retrieving stops
 * - Executing commands
 * - Returning computed or formatted results
 * - Managing trip-level properties
 * - XML output generation
 */
class TripPlanner : public IMOEDISPATCH
{
public:
	enum Methods 
	{
		SETPROPERTY = 1,		
	};

	/**
	 * @brief Constructs a new TripPlanner instance.
	 */
	TripPlanner();

	/**
	*@brief Destructor for TripPlanner.
	*/
	~TripPlanner();

	/**
	 * @brief Standard COM QueryInterface implementation.
	 * @param riid The requested interface ID.
	 * @param ppvObj Receives the interface pointer if supported.
	 * @return S_OK if the interface is supported, otherwise E_NOINTERFACE.
	 */
	HRESULT __stdcall QueryInterface(REFIID riid, LPVOID* ppvObj);
	
	/**
	 * @brief Increments the COM reference count.
	 * @return The new reference count.
	 */
	ULONG __stdcall AddRef();

	/**
	 * @brief Decrements the COM reference count and deletes the object when it reaches zero.
	 * @return The new reference count.
	 */
	ULONG __stdcall Release();

	HRESULT __stdcall Dispatch(IUnknown* iArgs);

	/**
	 * @brief Retrieves the trip's property collection.  The collection contains a list of IVARIABLE interfaces representing trip properties
	 * @param iProp Receives an IINTERFACECOLLECTION interface to the property collection.
	 * @return HRESULT indicating success or failure.
	 */
	HRESULT __stdcall Properties(IUnknown** iProp);

	/**
	 * @brief Executes a command string and sets the results to the m_properties return string.
	 * @param szCmd Command text.
	 * @return HRESULT indicating success or failure.
	 */
	HRESULT __stdcall Command(const wchar_t* szCmd);

	/**
	 * @brief Retrieves the return string generated by the last command.
	 * @param iStr Receives an ISTRING interface to the return string.
	 * @return HRESULT indicating success or failure.
	 */
	HRESULT __stdcall GetReturnString(IUnknown** iStr);

	/**
	 * @brief Creates and adds a new Stop object to the trip.
	 * @param iStop Receives an IUnknown interface to the newly created Stop.
	 * @return HRESULT indicating success or failure.
	 */
	HRESULT __stdcall AddStop(IUnknown** iStop);


	HRESULT __stdcall UnitTest();
	
	void WriteXML();
	Stop* GetStop(UINT ndx);
	void ReadXML();

private:
	int m_cRef;                     ///< COM reference count.
	InterfaceCollection m_stops;    ///< Collection of Stop objects.
	VLVariable* m_pName;            ///< Trip name variable.
	VariableCollection m_properties; ///< Trip-level properties.
	StringInf m_iRetStr;            ///< Return string for command results.
	double m_MPG;                   ///< Miles-per-gallon efficiency for the trip.

};
