var annotated_dup =
[
    [ "tinyxml2", null, [
      [ "Entity", "structtinyxml2_1_1_entity.html", null ],
      [ "StrPair", "classtinyxml2_1_1_str_pair.html", null ],
      [ "DynArray", "classtinyxml2_1_1_dyn_array.html", null ],
      [ "MemPool", "classtinyxml2_1_1_mem_pool.html", null ],
      [ "MemPoolT", "classtinyxml2_1_1_mem_pool_t.html", null ],
      [ "XMLVisitor", "classtinyxml2_1_1_x_m_l_visitor.html", "classtinyxml2_1_1_x_m_l_visitor" ],
      [ "XMLUtil", "classtinyxml2_1_1_x_m_l_util.html", null ],
      [ "XMLNode", "classtinyxml2_1_1_x_m_l_node.html", "classtinyxml2_1_1_x_m_l_node" ],
      [ "XMLText", "classtinyxml2_1_1_x_m_l_text.html", "classtinyxml2_1_1_x_m_l_text" ],
      [ "XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", "classtinyxml2_1_1_x_m_l_comment" ],
      [ "XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", "classtinyxml2_1_1_x_m_l_declaration" ],
      [ "XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", "classtinyxml2_1_1_x_m_l_unknown" ],
      [ "XMLAttribute", "classtinyxml2_1_1_x_m_l_attribute.html", "classtinyxml2_1_1_x_m_l_attribute" ],
      [ "XMLElement", "classtinyxml2_1_1_x_m_l_element.html", "classtinyxml2_1_1_x_m_l_element" ],
      [ "XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", "classtinyxml2_1_1_x_m_l_document" ],
      [ "XMLHandle", "classtinyxml2_1_1_x_m_l_handle.html", "classtinyxml2_1_1_x_m_l_handle" ],
      [ "XMLConstHandle", "classtinyxml2_1_1_x_m_l_const_handle.html", null ],
      [ "XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", "classtinyxml2_1_1_x_m_l_printer" ]
    ] ],
    [ "CommsInf", "class_comms_inf.html", null ],
    [ "Host", "class_host.html", null ],
    [ "IAREA", "struct_i_a_r_e_a.html", null ],
    [ "ICOMMGENERALPAGE", "struct_i_c_o_m_m_g_e_n_e_r_a_l_p_a_g_e.html", null ],
    [ "ICREATURE", "struct_i_c_r_e_a_t_u_r_e.html", null ],
    [ "IDATABASE", "struct_i_d_a_t_a_b_a_s_e.html", null ],
    [ "IDATETIME", "struct_i_d_a_t_e_t_i_m_e.html", null ],
    [ "IHOST", "struct_i_h_o_s_t.html", null ],
    [ "ILOGENTRY", "struct_i_l_o_g_e_n_t_r_y.html", null ],
    [ "IMODULE", "struct_i_m_o_d_u_l_e.html", null ],
    [ "InterfaceCollection", "class_interface_collection.html", null ],
    [ "InterfaceCollectionInf", "class_interface_collection_inf.html", "class_interface_collection_inf" ],
    [ "ITABLE", "struct_i_t_a_b_l_e.html", null ],
    [ "IUSER", "struct_i_u_s_e_r.html", null ],
    [ "JimboJonesLibrary", "class_jimbo_jones_library.html", null ],
    [ "JimboStringInf", "class_jimbo_string_inf.html", "class_jimbo_string_inf" ],
    [ "LOCATION", "struct_l_o_c_a_t_i_o_n.html", null ],
    [ "LogEntry", "class_log_entry.html", "class_log_entry" ],
    [ "LogEntryInf", "class_log_entry_inf.html", null ],
    [ "MoeInf", "class_moe_inf.html", null ],
    [ "Session", "class_session.html", null ],
    [ "Stop", "class_stop.html", "class_stop" ],
    [ "StringInf", "class_string_inf.html", "class_string_inf" ],
    [ "Testing", "class_testing.html", "class_testing" ],
    [ "TripPlanner", "class_trip_planner.html", "class_trip_planner" ],
    [ "TripPlannerInf", "class_trip_planner_inf.html", "class_trip_planner_inf" ],
    [ "User", "class_user.html", null ],
    [ "UserInf", "class_user_inf.html", null ],
    [ "VariableCollection", "class_variable_collection.html", null ],
    [ "VLDateTime", "class_v_l_date_time.html", null ],
    [ "VLString", "class_v_l_string.html", null ],
    [ "VLStringCollection", "class_v_l_string_collection.html", null ],
    [ "VLVariable", "class_v_l_variable.html", null ]
];